export const products = [
    {
        nombreComercial: "TRAVELGUM",
        laboratorio: "Microsules Argentina",
        monodroga: "Tamsulosina 0,4mg 30 capsulas",
        stock: 1,
        price: "40%",
        priceDiscount: "70%",
        dto: 600,
        id: 4,
        precioConDescuento: 180,
        image: "https://via.placeholder.com/300",
        pami: 0
    },
    {
        nombreComercial: "MICRO-CAPE 75",
        laboratorio: "Microsules Argentina",
        monodroga: "Clopidogrel 75 mg",
        stock: 1,
        price: "40%",
        priceDiscount: "70%",
        dto: 500,
        id: 5,
        precioConDescuento: 150,
        image: "https://via.placeholder.com/300",
        pami: 1
    },
    {
        nombreComercial: "TURBULINA",
        laboratorio: "Microsules Argentina",
        monodroga: "Rosuvastatina 10 mg",
        stock: 0,
        price: "40%",
        priceDiscount: "70%",
        dto: 850,
        id: 6,
        precioConDescuento: 255,
        image: "https://via.placeholder.com/300",
        pami: 1
    },
    {
        nombreComercial: "IBUPROFENO FORTE",
        laboratorio: "Klonal",
        monodroga: "Ibuprofeno 4% (Suspensión 90 ml)",
        stock: -1,
        price: "35%",
        priceDiscount: "65%",
        dto: 400,
        id: 7,
        precioConDescuento: 120,
        image: "https://via.placeholder.com/300",
        pami: 0
    },
    {
        nombreComercial: "SALBUDEM",
        laboratorio: "Denver Farma",
        monodroga: "Pantoprazol 20 mg (30 comprimidos)",
        stock: 0,
        price: "40%",
        priceDiscount: "70%",
        dto: 900,
        precioConDescuento: 270,
        image: "https://via.placeholder.com/300",
        pami: 1,
        id: 9
    },
    {
        nombreComercial: "SULFADINA DE PLATA DF",
        laboratorio: "Denver Farma",
        monodroga: "Prednisolona 1.0% Fenilefrina 0.12% (10 ml)",
        stock: -1,
        price: "40%",
        priceDiscount: "70%",
        dto: 800,
        precioConDescuento: 240,
        image: "https://via.placeholder.com/300",
        pami: 1,
        id: 14
    }
]